spring:
  datasource:
    username: root
    password: gsz1125
    url: jdbc:mysql://127.0.0.1:3306/blog
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
  session:
    timeout: 10m
server:
  servlet:
    context-path: /blog

